version: '3.8'

services:

  db:
    user: root
    image: postgres:16.3-alpine3.19
    container_name: "${COMPOSE_PROJECT_NAME}_db"
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - ./docker/volumes/${COMPOSE_PROJECT_NAME}_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 10s
      timeout: 5s
      retries: 5
    logging: &logging
      driver: json-file
      options:
        max-size: "512m"
        max-file: "3"

  pgadmin:
    user: root
    image: dpage/pgadmin4
    container_name: "${COMPOSE_PROJECT_NAME}_pgadmin"
    restart: unless-stopped
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:80"
    expose:
      - "${PGADMIN_EXTERNAL_PORT}"
    env_file:
      - .env
    volumes:
      - ./docker/volumes/${COMPOSE_PROJECT_NAME}_pgadmin:/var/lib/pgadmin
    logging: *logging

  app:
    container_name: "${COMPOSE_PROJECT_NAME}_app"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${APP_EXTERNAL_PORT}:8000"
    expose:
      - "${APP_EXTERNAL_PORT}"
    env_file:
      - .env
    depends_on:
      - db
    logging: *logging

  migration:
    container_name: "${COMPOSE_PROJECT_NAME}_db_migration"
    build:
      context: .
      dockerfile: Dockerfile.migration.dockerfile
    env_file:
      - .env
    depends_on:
      - db
    logging: *logging