version: '3.8'

services:

  db:
    user: root
    image: postgres:16.3-alpine3.19
    container_name: "${COMPOSE_PROJECT_NAME}_db"
    restart: unless-stopped
    ports:
      - "${POSTGRES_PORT}:5432"
    expose:
      - "${POSTGRES_PORT}"
    volumes:
      - ./docker/volumes/${COMPOSE_PROJECT_NAME}_postgres_data:/var/lib/postgresql/data
    env_file:
      - .env
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres" ]
      interval: 2s
      timeout: 5s
      retries: 10
      start_period: 3s
    logging: &logging
      driver: json-file
      options:
        max-size: "512m"
        max-file: "3"

  pgadmin:
    user: root
    image: dpage/pgadmin4
    container_name: "${COMPOSE_PROJECT_NAME}_pgadmin"
    restart: unless-stopped
    ports:
      - "${PGADMIN_EXTERNAL_PORT}:80"
    expose:
      - "${PGADMIN_EXTERNAL_PORT}"
    env_file:
      - .env
    volumes:
      - ./docker/volumes/${COMPOSE_PROJECT_NAME}_pgadmin:/var/lib/pgadmin
    logging: *logging

  app:
    container_name: "${COMPOSE_PROJECT_NAME}_app"
    restart: unless-stopped
    build:
      context: .
      dockerfile: Dockerfile
#    command: uvicorn --factory app.main:create_app --host 0.0.0.0 --port 8000
    command: uvicorn --factory app.main:create_app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - .:/app
    ports:
      - "${APP_EXTERNAL_PORT}:8000"
    expose:
      - "${APP_EXTERNAL_PORT}"
    env_file:
      - .env
    depends_on:
      - migration
    logging: *logging

  migration:
    container_name: "${COMPOSE_PROJECT_NAME}_migration"
    build:
      context: .
      dockerfile: Dockerfile
    command: alembic upgrade head
    env_file:
      - .env
    depends_on:
      db:
        condition: service_healthy
    logging: *logging

#  tests:
#    container_name: "${COMPOSE_PROJECT_NAME}_tests"
#    build:
#      context: .
#      dockerfile: Dockerfile
#    command: pytest
#    env_file:
#      - .env
#    logging: *logging
